# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0061962ca79b540eb689ea568a469fad9d69f42664a42167617b731a3c62f2ac8bc7c0ed3b8ec45ac5a2910b4be0b07860fe4321652c323959a867f1c190a0a6

test:
  secret_key_base: 2750a5db3b2e5baa7de73fbd07949e2784247505be1bbb47fa6f1f604da41b4ddd62083b373e208fe6fc495330e726308eba67fd6a40bb0ff93490ad091b7714

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
